apiVersion: v1
kind: Service
metadata:
  name: nginx-prod
  namespace: prod
  labels:
    app: nginx
    env: prod
spec:
  type: ClusterIP
  selector:
    app: nginx
    env: prod
  ports:
    - port: 80
      targetPort: 80
